=== eldereis/intelijans/rets/server/src/etc/rets10.dtd
<!-- <!DOCTYPE REData SYSTEM "REData-20001001.dtd"> -->
<!-- <!DOCTYPE REData [ -->
<!--   Real Estate Transaction Specification (RETS) DTD  -->
<!--   Real Estate Transaction Markup Language (RETML)  -->
<!--
	submitted by:
	Dan Musso
	WyldFyre Technologies, Inc.
	Version 1.0  11/02/1999
-->

<!-- BASIC ELEMENTS -->

<!--DATE/TIME ELEMENTS -->
<!--see ISO 8601 for acceptable values for Format -->
<!ELEMENT YearBuilt (#PCDATA) >
<!ATTLIST YearBuilt
Type CDATA #FIXED "DATE"
Format CDATA #FIXED "YYYY"
NewConstruction (Yes | No) "No">
<!ELEMENT CloseDate (#PCDATA) >
<!ATTLIST CloseDate
Type CDATA #FIXED "DATE"
Format CDATA #FIXED "YYYY-MM-DD" >
<!ELEMENT ExpirationDate (#PCDATA) >
<!ATTLIST ExpirationDate
Type CDATA #FIXED "DATE"
Format CDATA #FIXED "YYYY-MM-DD" >
<!ELEMENT ListDate (#PCDATA) >
<!ATTLIST ListDate
Type CDATA #FIXED "DATE"
Format CDATA #FIXED "YYYY-MM-DD" >
<!ELEMENT ContractDate (#PCDATA) >
<!ATTLIST ContractDate
Type CDATA #FIXED "DATE"
Format CDATA #FIXED "YYYY-MM-DD" >
<!ELEMENT StatusChangeDate (#PCDATA) >
<!ATTLIST StatusChangeDate
Type CDATA #FIXED "DATE"
Format CDATA #FIXED "YYYY-MM-DD" >
<!ELEMENT ModificationTimestamp (#PCDATA) >
<!ATTLIST ModificationTimestamp
Type CDATA #FIXED "DATE-TIME"
Format CDATA #FIXED "YYYY-MM-DDThh:mm:ss[.sss]" >
<!-- MONETARY ELEMENTS -->
<!--see ISO 4217 for acceptable values for CurrencyCode -->
<!ELEMENT AssessedValuation (#PCDATA) >
<!ATTLIST AssessedValuation
Type (INTEGER | FLOAT) "INTEGER"
CurrencyCode CDATA "USD" >
<!ELEMENT AssociationFee (#PCDATA) >
<!ATTLIST AssociationFee
Type (INTEGER | FLOAT) "INTEGER"
CurrencyCode CDATA "USD"
Period (Day | Week | Month | Year | Fixed) "Month">
<!ELEMENT ClosePrice (#PCDATA) >
<!ATTLIST ClosePrice
Type (INTEGER | FLOAT) "INTEGER"
CurrencyCode CDATA "USD" >
<!ELEMENT Expenses (#PCDATA) >
<!ATTLIST Expenses
Type (INTEGER | FLOAT) "INTEGER"
CurrencyCode CDATA "USD" 
Period (Day | Week | Month | Year | Fixed) "Year">
<!ELEMENT GrossIncome (#PCDATA) >
<!ATTLIST GrossIncome
Type (INTEGER | FLOAT) "INTEGER"
CurrencyCode CDATA "USD" 
Period (Day | Week | Month | Year | Fixed) "Year">
<!ELEMENT ListPrice (#PCDATA) >
<!ATTLIST ListPrice
Type (INTEGER | FLOAT) "INTEGER"
CurrencyCode CDATA "USD" >
<!ELEMENT NetIncome (#PCDATA) >
<!ATTLIST NetIncome
Type (INTEGER | FLOAT) "INTEGER"
CurrencyCode CDATA "USD" >
<!ELEMENT OriginalListPrice (#PCDATA) >
<!ATTLIST OriginalListPrice
Type (INTEGER | FLOAT) "INTEGER"
CurrencyCode CDATA "USD" >
<!ELEMENT RentIncome (#PCDATA) >
<!ATTLIST RentIncome
Type (INTEGER | FLOAT) "INTEGER"
CurrencyCode CDATA "USD" 
Period (Day | Week | Month | Year | Fixed) "Year">
<!-- NUMERIC ELEMENTS -->
<!ELEMENT BathsTotal (#PCDATA) >
<!ATTLIST BathsTotal
Type CDATA #FIXED "FLOAT" >
<!ELEMENT BathsFull (#PCDATA) >
<!ATTLIST BathsFull
Type CDATA #FIXED "INTEGER" >
<!ELEMENT BathsHalf (#PCDATA) >
<!ATTLIST BathsHalf
Type CDATA #FIXED "INTEGER" >
<!ELEMENT BathsThreeQuarter (#PCDATA) >
<!ATTLIST BathsThreeQuarter
Type CDATA #FIXED "INTEGER" >
<!ELEMENT Bedrooms (#PCDATA) >
<!ATTLIST Bedrooms
Type CDATA #FIXED "INTEGER" >
<!ELEMENT CarPort (#PCDATA) >
<!ATTLIST CarPort
Type (INTEGER | FLOAT) "INTEGER" >
<!ELEMENT Commission (#PCDATA) >
<!ATTLIST Commission
Type CDATA #FIXED "FLOAT"
Value (Percent | Currency) "Percent" 
CurrencyCode CDATA "USD" >
<!ELEMENT CoveredParking (#PCDATA) >
<!ATTLIST CoveredParking
Type CDATA #FIXED "INTEGER" >
<!ELEMENT DaysOnMarket (#PCDATA) >
<!ATTLIST DaysOnMarket
Type CDATA #FIXED "INTEGER" >
<!ELEMENT Fireplaces (#PCDATA) >
<!ATTLIST Fireplaces
Type CDATA #FIXED "INTEGER" >
<!ELEMENT Garage (#PCDATA) >
<!ATTLIST Garage
Type (INTEGER | FLOAT) "INTEGER" 
Style (Attached | Detached ) "Attached" >
<!ELEMENT Latitude (#PCDATA) >
<!ATTLIST Latitude
Type CDATA #FIXED "FLOAT" >
<!ELEMENT Length (#PCDATA) >
<!ATTLIST Length
Type (INTEGER | FLOAT) "INTEGER" >
<!ELEMENT Longitude (#PCDATA) >
<!ATTLIST Longitude
Type CDATA #FIXED "FLOAT" >
<!ELEMENT OpenParking (#PCDATA) >
<!ATTLIST OpenParking
Type CDATA #FIXED "INTEGER" >
<!ELEMENT Stories (#PCDATA) >
<!ATTLIST Stories
Type (INTEGER | FLOAT) "INTEGER" >
<!ELEMENT TotalRooms (#PCDATA) >
<!ATTLIST TotalRooms
Type CDATA #FIXED "INTEGER" >
<!ELEMENT TotalUnits (#PCDATA) >
<!ATTLIST TotalUnits
Type CDATA #FIXED "INTEGER" >
<!ELEMENT VacancyFactor (#PCDATA) >
<!ATTLIST VacancyFactor
Type CDATA #FIXED "FLOAT"
Value (Percent | Decimal) "Percent" >
<!ELEMENT Width (#PCDATA) >
<!ATTLIST Width
Type (INTEGER | FLOAT) "INTEGER" >
<!-- DIMENSIONAL ELEMENTS -->
<!ELEMENT Area ( #PCDATA) >
<!ATTLIST Area
Units (SqFeet | SqMeters | Acres | Hectares) "SqFeet"
Type (INTEGER | FLOAT | TEXT) "INTEGER" >
<!ELEMENT Dimensions ( #PCDATA)>
<!ATTLIST Dimensions
Units (Feet | Meters | Unspecified ) "Feet" 
Type CDATA #FIXED "TEXT">

<!ELEMENT Basement (Area?, Dimensions?, Length?, Width?) >
<!ATTLIST Basement
Present (Yes | No) "Yes">
<!ELEMENT DiningRoom (Area?, Dimensions?, Length?, Width?) >
<!ATTLIST DiningRoom
Present (Yes | No) "Yes">
<!ELEMENT FamilyRoom (Area?, Dimensions?, Length?, Width?) >
<!ATTLIST FamilyRoom
Present (Yes | No) "Yes">
<!ELEMENT LivingRoom (Area?, Dimensions?, Length?, Width?) >
<!ATTLIST LivingRoom
Present (Yes | No) "Yes">
<!ELEMENT LotSize (Area?, Dimensions?, Length?, Width?) >

<!ELEMENT LivingArea (Area?) > <!-- a.k.a. square footage -->


<!-- YES/NO TEXT ELEMENTS -->
<!ELEMENT Cooling (#PCDATA) >
<!ATTLIST Cooling
Present (Yes | No) "Yes">
<!ELEMENT Heating (#PCDATA) >
<!ATTLIST Heating
Present (Yes | No) "Yes">
<!ELEMENT Laundry (#PCDATA) >
<!ATTLIST Laundry
Present (Yes | No) "Yes">
<!ELEMENT Pool (#PCDATA) >
<!ATTLIST Pool
Present (Yes | No) "Yes">
<!ELEMENT Utilities (#PCDATA) >
<!ATTLIST Utilities
Present (Yes | No) "Yes">
<!ELEMENT View (#PCDATA) >
<!ATTLIST View
Present (Yes | No) "Yes">
<!ELEMENT WaterFront (#PCDATA) >
<!ATTLIST WaterFront
Present (Yes | No) "Yes">

<!-- TEXT ELEMENTS -->
<!ELEMENT AgentID (#PCDATA) >
<!ELEMENT BoxNumber (#PCDATA) >
<!ELEMENT BrokerID (#PCDATA) >
<!ELEMENT BuildingName (#PCDATA) >
<!ELEMENT BuildingType (#PCDATA) >
<!ELEMENT CarrierRoute (#PCDATA) >
<!ELEMENT CellPhone (#PCDATA) >
<!ELEMENT City (#PCDATA) >
<!ELEMENT ComplexFeatures (#PCDATA) >
<!ELEMENT CopyrightNotice (#PCDATA) >
<!ELEMENT Country (#PCDATA) >
<!ELEMENT County (#PCDATA) >
<!ELEMENT DevelopmentStatus (#PCDATA) >
<!ELEMENT Directions (#PCDATA) >
<!ELEMENT Disclaimer (#PCDATA) >
<!ELEMENT ElementarySchool (#PCDATA) >
<!ELEMENT Email (#PCDATA) >
<!ELEMENT ExistingStructures (#PCDATA) >
<!ELEMENT Exterior (#PCDATA) >
<!ELEMENT ExteriorFeatures (#PCDATA) >
<!ELEMENT Fax (#PCDATA) >
<!ELEMENT FirstName (#PCDATA) >
<!ELEMENT HighSchool (#PCDATA) >
<!ELEMENT HomePhone (#PCDATA) >
<!ELEMENT InteriorFeatures (#PCDATA) >
<!ELEMENT LastName (#PCDATA) >
<!ELEMENT LegalDescription (#PCDATA) >
<!ELEMENT ListingArea (#PCDATA) >
<!ELEMENT ListingID (#PCDATA) >
<!ELEMENT ListingServiceName (#PCDATA) >
<!ELEMENT ListingType (#PCDATA) >
<!ELEMENT MapCoordinate (#PCDATA) >
<!ELEMENT MiddleSchool (#PCDATA) >
<!ELEMENT Name (#PCDATA) >
<!ELEMENT NRDSMemberID (#PCDATA) >
<!ELEMENT NRDSOfficeID (#PCDATA) >
<!ELEMENT OfficeID (#PCDATA) >
<!ELEMENT OfficePhone (#PCDATA) >
<!ELEMENT OwnerPays (#PCDATA) >
<!ELEMENT Ownership (#PCDATA) >
<!ELEMENT OwnersName (#PCDATA) >
<!ELEMENT Pager (#PCDATA) >
<!ELEMENT ParcelAccess (#PCDATA) >
<!ELEMENT ParcelMapURL (#PCDATA) >
<!ELEMENT ParcelNumber (#PCDATA) >
<!ELEMENT PictureCaption (#PCDATA) >
<!ELEMENT PictureID (#PCDATA) >
<!ELEMENT PostalCode (#PCDATA) >
<!ELEMENT PresentUse (#PCDATA) >
<!ELEMENT PropertyZoning (#PCDATA) >
<!ELEMENT PublicRemarks (#PCDATA) >
<!ELEMENT Remarks (#PCDATA) >
<!ELEMENT Roof (#PCDATA) >
<!ELEMENT SchoolDistrict (#PCDATA) >
<!ELEMENT ShowingInstructions (#PCDATA) >
<!ELEMENT StateOrProvince (#PCDATA) >
<!ELEMENT StreetAdditionalInfo (#PCDATA) >
<!ELEMENT StreetDirPrefix (#PCDATA) >
<!ELEMENT StreetDirSuffix (#PCDATA) >
<!ELEMENT StreetName (#PCDATA) >
<!ELEMENT StreetNumber (#PCDATA) >
<!ELEMENT StreetSuffix (#PCDATA) >
<!ELEMENT Style (#PCDATA) >
<!ELEMENT Subdivision (#PCDATA) >
<!ELEMENT TaxID (#PCDATA) >
<!ELEMENT TenantPays (#PCDATA) >
<!ELEMENT Topography (#PCDATA) >
<!ELEMENT Type (#PCDATA) >
<!ELEMENT UnitNumber (#PCDATA) >
<!ELEMENT URL (#PCDATA) >
<!ATTLIST URL
Internal (Yes | No) "No">
<!ELEMENT Unstructured (#PCDATA) >
<!ELEMENT Zoning (#PCDATA) >

<!-- COMPOUND ELEMENTS -->
<!ELEMENT ResidentialProperty (Listing, Bedrooms, Baths, Subdivision?, AssociationFee?, LivingArea?, LotSize?, Parking?, Stories?, YearBuilt?, Heating?, Cooling?, Pool?, InteriorFeatures?, ExteriorFeatures?, Type?, Style?, Rooms?, Occupant?, WaterFront?, Fireplaces?, Roof?, Exterior? ) >
<!ELEMENT CommonInterest (ResidentialProperty, Complex) >
<!ELEMENT LotsAndLand (Listing, LotSize, Utilities?, PresentUse?, Topography?, ParcelAccess?, DevelopmentStatus?, ExistingStructures?) >
<!ELEMENT MultiFamily (Listing, Complex, RentIncome?, GrossIncome?, Expenses?, NetIncome?, VacancyFactor?, TenantPays?, OwnerPays?, Laundry?, Subdivision?, AssociationFee?, LivingArea?, LotSize?, Parking?, Stories?, YearBuilt?, Heating?, Cooling?, Pool?, InteriorFeatures?, ExteriorFeatures?, Type?, Style?, WaterFront?, Roof?, Exterior?, Unit*) >
<!ELEMENT Complex ( BuildingType, TotalUnits, BuildingName?, ComplexFeatures?) >
<!ELEMENT Listing (StreetAddress, ListingData, MLSInformation, GeographicData, ModificationTimestamp, ListingID, Zoning?, SalesData?, SchoolData?, TaxData?, ParcelNumber?, View?, CopyrightNotice?, Disclaimer? , PictureData*) >
<!ELEMENT Unit (Bedrooms, Baths, RentIncome?, AssociationFee?, LivingArea?, Parking?, Stories?, Heating?, Cooling?, InteriorFeatures?, Rooms?, Occupant?, Fireplaces?) >
<!ELEMENT GeographicData (Latitude, Longitude, County?, Directions?, MapCoordinate?, URL?) >
<!ELEMENT SchoolData (SchoolDistrict?, ElementarySchool?, MiddleSchool?, HighSchool?) >
<!ELEMENT TaxData (StreetAddress, MailingAddress, TaxID, County, ModificationTimestamp?, LegalDescription?, OwnersName?, AssessedValuation?, PropertyZoning?, ParcelMapURL?) >
<!ELEMENT PictureData (PictureID?, ModificationTimestamp?, URL, PictureCaption?) >
<!ELEMENT REOffice (Name?, ContactInformation?, StreetAddress?, ListingServiceName?, OfficeID?, BrokerID?, NRDSOfficeID?) >
<!ELEMENT REAgent (FirstName?, LastName?, ContactInformation?, StreetAddress?, ListingServiceName?, AgentID?, NRDSMemberID?) >
<!ELEMENT Occupant (Name?, ContactInformation?) >
<!ELEMENT ContactInformation (OfficePhone?,  CellPhone?, HomePhone?, Fax?, Pager?, Email?, URL?) >
<!ELEMENT StreetAddress ((StreetNumber?, BoxNumber?, StreetDirPrefix?, StreetName, StreetAdditionalInfo?, StreetDirSuffix?, StreetSuffix?, UnitNumber?, City?, StateOrProvince?, Country?, PostalCode?, CarrierRoute?) | Unstructured ) >
<!ELEMENT MailingAddress (StreetAddress) >
<!ELEMENT ListingData (REAgent+, REOffice, ListDate, ListPrice, ExpirationDate?, ShowingInstructions?, ListingType?, Commission?, Remarks?, PublicRemarks?) >
<!ELEMENT SalesData (REAgent+, REOffice, ContractDate, ClosePrice?, CloseDate?) >
<!ELEMENT MLSInformation (ListingStatus, OriginalListPrice?, ListingArea?, StatusChangeDate?, DaysOnMarket?, ListingServiceName?) >
<!ELEMENT ListingStatus (#PCDATA) >
<!ATTLIST ListingStatus
Status (Active | Closed | Expired | OffMarket | Pending) #REQUIRED >
<!ELEMENT Baths (BathsTotal, BathsFull?, BathsHalf?, BathsThreeQuarter?) >
<!ELEMENT Parking (Garage?, CarPort?, OpenParking?, CoveredParking?) >
<!ELEMENT Rooms (DiningRoom?, LivingRoom?, FamilyRoom?, Basement?, TotalRooms?) >
<!-- PACKAGING ELEMENTS -->
<!ELEMENT REData (REProperties?, REOffices?, REAgents?, REOfficeRosters?) >
<!ELEMENT REProperties (CopyrightNotice?, Disclaimer?, ResidentialProperty*, CommonInterest*, LotsAndLand*, MultiFamily*, TaxData*) >
<!ELEMENT REOfficeRosters (REOfficeRoster+) >
<!ELEMENT REOfficeRoster (REOffice, REAgent+) >
<!ELEMENT REAgents (REAgent+) >
<!ELEMENT REOffices (REOffice+) >
<!-- ]> -->

=== eldereis/intelijans/rets/server/src/etc/ResidentialProperty.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE ResidentialProperty SYSTEM "http://localhost:8080/rets/rets10.dtd"> -->
<ResidentialProperty>
  <Listing>
    <StreetAddress>
      <StreetNumber>OBJECT:Property;ATTRIBUTE:StreetNumber</StreetNumber>
      <BoxNumber/>
      <StreetDirPrefix/>
      <StreetName>OBJECT:Property;ATTRIBUTE:StreetName</StreetName>
      <StreetAdditionalInfo/>
      <StreetDirSuffix/>
      <UnitNumber/>
      <City>OBJECT:Property;ATTRIBUTE:City</City>
      <StateOrProvince>OBJECT:Property;ATTRIBUTE:State</StateOrProvince>
      <Country>OBJECT:Property;ATTRIBUTE:Country</Country>
      <PostalCode>OBJECT:Property;ATTRIBUTE:PostalCode</PostalCode>
      <CarrierRoute>OBJECT:Property;ATTRIBUTE:CarrierRoute</CarrierRoute>
    </StreetAddress>
    <ListingData>
      <REAgent>
        <AgentID>OBJECT:Property;ATTRIBUTE:ListAgentAgentID</AgentID>
      </REAgent>
      <REOffice>
        <OfficeID>OBJECT:Property;ATTRIBUTE:ListOfficeOfficeID</OfficeID>
        <BrokerID>OBJECT:Property;ATTRIBUTE:AgentCoList</BrokerID>
      </REOffice>
      <ListDate Format="YYYY-MM-DD" Type="DATE">OBJECT:Property;ATTRIBUTE:ListDate</ListDate>
      <ListPrice>OBJECT:Property;ATTRIBUTE:ListPrice</ListPrice>
      <ExpirationDate Format="YYYY-MM-DD" Type="DATE">OBJECT:Property;ATTRIBUTE:ExpireDate</ExpirationDate>
      <ShowingInstructions>OBJECT:Property;ATTRIBUTE:ShowInstr</ShowingInstructions>
      <ListingType>OBJECT:Property;ATTRIBUTE:ListType</ListingType>
      <Commission CurrencyCode="USD" Type="FLOAT" Value="Currency">OBJECT:Property;ATTRIBUTE:CompBuy</Commission>
      <Remarks>OBJECT:Property;ATTRIBUTE:RealRemarks</Remarks>
      <PublicRemarks>OBJECT:Property;ATTRIBUTE:Remarks</PublicRemarks>
    </ListingData>
    <MLSInformation>
      <ListingStatus Status="Active"/>
      <OriginalListPrice>OBJECT:Property;ATTRIBUTE:ListPriceOrig</OriginalListPrice>
    </MLSInformation>
    <GeographicData>
      <Latitude/>
      <Longitude/>
      <County>OBJECT:Property;ATTRIBUTE:County</County>
      <Directions>OBJECT:Property;ATTRIBUTE:Directions</Directions>
      <MapCoordinate>OBJECT:Property;ATTRIBUTE:Map</MapCoordinate>
      <URL/>
    </GeographicData>
    <ModificationTimestamp/>
    <ListingID>OBJECT:Property;ATTRIBUTE:ListingID</ListingID>
    <SalesData>
      <REAgent/>
      <REOffice/>
      <ContractDate>OBJECT:Property;ATTRIBUTE:OffMarketDate</ContractDate>
      <ClosePrice>OBJECT:Property;ATTRIBUTE:SalesPrice</ClosePrice>
      <CloseDate>OBJECT:Property;ATTRIBUTE:ClosedDate</CloseDate>
    </SalesData>
    <SchoolData>
      <SchoolDistrict>OBJECT:Property;ATTRIBUTE:SchoolDistrict</SchoolDistrict>
      <HighSchool>OBJECT:Property;ATTRIBUTE:SchoolHigh</HighSchool>
    </SchoolData>
    <PictureData>
      <URL/>
    </PictureData>
  </Listing>
  <Bedrooms Type="INTEGER">OBJECT:Property;ATTRIBUTE:Beds</Bedrooms>
  <Baths>
    <BathsTotal>OBJECT:Property;ATTRIBUTE:BathsTotal</BathsTotal>
    <BathsFull>OBJECT:Property;ATTRIBUTE:BathsFull</BathsFull>
    <BathsHalf>OBJECT:Property;ATTRIBUTE:BathsHalf</BathsHalf>
  </Baths>
  <YearBuilt Format="YYYY" NewConstruction="No" Type="DATE">OBJECT:Property;ATTRIBUTE:YearBuilt</YearBuilt>
  <Type>OBJECT:Property;ATTRIBUTE:Type</Type>
  <Style>OBJECT:Property;ATTRIBUTE:Style</Style>
</ResidentialProperty>
